<?php
require_once("config.php");
include_once "functions-tena.php";

if (!isset($_SESSION['user_id']) || $_SESSION['user_role'] != 'admin') {
    header("Location: login.php");
    exit();
}

$user_role = $_SESSION['user_role'];

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    // Personal Info
    $firstName = $_POST["first_name"];
    $lastName = $_POST["last_name"];
    $email = $_POST["email"];
    $phone = $_POST["phone_number"];
    $county = $_POST["county"];
    $townCentre = $_POST["town_centre"];

    // KYC Documents
    $nationalId = $_POST["national_id"];
    $nssf = $_POST["nssf"];
    $nhif = $_POST["nhif"];
    $kraPin = $_POST["kra_pin"];
    $dateOfOnboarding = date("Y-m-d");
    $residenceBuilding = $_POST["residence_nearest_building"];
    $residenceRoad = $_POST["residence_nearest_road"];

    // Bio Data
    $age = $_POST["age"];
    $gender = $_POST["gender"];
    $nextOfKinName = $_POST["next_of_kin_name"];
    $nextOfKinPhone = $_POST["next_of_kin_phone"];
    $nextOfKinRelation = $_POST["next_of_kin_relation"];

    // Directory for uploads
    $uploadDir = 'uploads/';
    if (!is_dir($uploadDir)) {
        mkdir($uploadDir, 0777, true);
    }

    // File upload handling
    $idPhotoFront = '';
    $idPhotoBack = '';

    // Handle ID photo front upload
    if (isset($_FILES['id_photo_front']) && $_FILES['id_photo_front']['error'] === UPLOAD_ERR_OK) {
        if ($_FILES['id_photo_front']['size'] <= 2 * 1024 * 1024) { // Check if file size is <= 2MB
            $fileExt = pathinfo($_FILES['id_photo_front']['name'], PATHINFO_EXTENSION);
            $validExt = ['jpg', 'jpeg', 'png', 'pdf'];
            if (in_array(strtolower($fileExt), $validExt)) {
                $idPhotoFront = $uploadDir . 'front_' . uniqid() . '.' . $fileExt;
                move_uploaded_file($_FILES['id_photo_front']['tmp_name'], $idPhotoFront);
            } else {
                $error = "Invalid file type for front ID photo.";
            }
        } else {
            $error = "Front ID photo exceeds the 2MB limit.";
        }
    }

    // Handle ID photo back upload
    if (isset($_FILES['id_photo_back']) && $_FILES['id_photo_back']['error'] === UPLOAD_ERR_OK) {
        if ($_FILES['id_photo_back']['size'] <= 2 * 1024 * 1024) { // Check if file size is <= 2MB
            $fileExt = pathinfo($_FILES['id_photo_back']['name'], PATHINFO_EXTENSION);
            $validExt = ['jpg', 'jpeg', 'png', 'pdf'];
            if (in_array(strtolower($fileExt), $validExt)) {
                $idPhotoBack = $uploadDir . 'back_' . uniqid() . '.' . $fileExt;
                move_uploaded_file($_FILES['id_photo_back']['tmp_name'], $idPhotoBack);
            } else {
                $error = "Invalid file type for back ID photo.";
            }
        } else {
            $error = "Back ID photo exceeds the 2MB limit.";
        }
    }

    // Check if manager already exists
    if (!isset($error) && managerExists($email, $phone, $nationalId)) {
        $error = "Manager already exists.";
    } else if (!isset($error)) {
        // Insert manager data into the managers table
        $stmt = $conn->prepare("INSERT INTO managers (first_name, last_name, email, phone_number, county, town_centre, national_id, id_photo_front, id_photo_back, nssf, nhif, kra_pin, date_of_onboarding, residence_nearest_building, residence_nearest_road, age, gender, next_of_kin_name, next_of_kin_phone_number, next_of_kin_relation) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

        if ($stmt) {
            $stmt->bind_param("ssssssssssssssssssss", $firstName, $lastName, $email, $phone, $county, $townCentre, $nationalId, $idPhotoFront, $idPhotoBack, $nssf, $nhif, $kraPin, $dateOfOnboarding, $residenceBuilding, $residenceRoad, $age, $gender, $nextOfKinName, $nextOfKinPhone, $nextOfKinRelation);

            if ($stmt->execute()) {
                // Retrieve the manager_id generated by the trigger
                $stmt->close();
                $result = $conn->query("SELECT manager_id FROM managers WHERE email = '$email'");
                if ($result && $result->num_rows > 0) {
                    $row = $result->fetch_assoc();
                    $generatedManagerId = $row['manager_id'];

                    // Create user with role 'manager' and random password
                    $password = generatePassword();
                    // Hash the password
                    $hashed_password = password_hash($password, PASSWORD_DEFAULT);
                    $stmt = $conn->prepare("INSERT INTO users (first_name, last_name, file_no, email, password, role) VALUES (?, ?, ?, ?, ?, 'manager')");
                    if ($stmt) {
                        $stmt->bind_param("sssss", $firstName, $lastName, $generatedManagerId, $email, $hashed_password);
                        if ($stmt->execute()) {
                            // Send email to manager with details and temporary password
                            $to = $email;
                            $subject = "Welcome to Our Platform";
                            $message = "Dear $firstName,\n\n";
                            $message .= "Thank you for joining us. Below are your details:\n\n";
                            $message .= "Manager/Work ID: $generatedManagerId\n";
                            $message .= "Email: $email\n";
                            $message .= "Temporary Password: $password\n\n";
                            $message .= "You can log in to your dashboard at https://portal.omabracredit.co.ke as manager using your email and this temporary password.\n\n";
                            $message .= "Best regards,\nAdministrator.";

                            sendEmail($to, $subject, $message);

                            $insertQuerySuccess = "Form submitted successfully! Manager should receive email with their details and a temporary password.";

                            echo '<script>alert("Form submitted successfully! Manager should receive email with their details and a temporary password.");</script>';
                        } else {
                            $error = "Error creating user: " . $stmt->error;
                        }
                        $stmt->close();
                    } else {
                        $error = "Error preparing user statement: " . $conn->error;
                    }
                } else {
                    $error = "Error fetching manager_id: " . $conn->error;
                }
            } else {
                $error = "Error executing manager statement: " . $stmt->error;
            }
        } else {
            $error = "Error preparing manager statement: " . $conn->error;
        }
    }
}

if (isset($error)) {
    echo '<script>alert("'.$error.'");</script>';
}
?>


<!DOCTYPE html>
<html>
<?php require_once("head.php"); ?>
    <body>
        <?php require_once("header.php"); ?>
        <?php require_once("right-sidebar.php"); ?>

		<?php
		// Include the appropriate sidebar based on the user role
		if ($user_role == 'admin') {
			include('left-sidebar-admin.php');
		} elseif ($user_role == 'manager') {
			include('left-sidebar-manager.php');
		} elseif ($user_role == 'client') {
			include('left-sidebar-client.php');
		} else {
			// If the user role is neither admin, manager, nor client, redirect or show an error
			header("Location: login.php");
			exit();
		}
		?>

    <!-- Manager Onboarding Form -->
	<div class="main-container">
    <div class="xs-pd-20-10 pd-ltr-20">
        <div class="page-header">
            <div class="row">
                <div class="col-md-6 col-sm-12">
                    <!-- Page title and breadcrumb -->
                    <div class="title">
                        <h4>On-Boarding</h4>
                    </div>
                    <nav aria-label="breadcrumb" role="navigation">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">
                                Manager On-Boarding
                            </li>
                        </ol>
                    </nav>
                </div>
                <div class="col-md-6 col-sm-12 text-right">
                </div>
            </div>
        </div>

        <div class="pd-20 card-box mb-30">
            <div class="clearfix">
                <h4 class="text-blue h4">Please register manager</h4>
                <p class="mb-30">All fields required: If not applicable enter "NA" in caps lock</p>
            </div>
            <div class="wizard-content">
            <form class="tab-wizard wizard-circle wizard" method="POST" enctype="multipart/form-data" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>">
                <!-- Form sections go here -->
                <?php 
                if (isset($error)) {
                    echo '<p style="color:red;">' . htmlspecialchars($error) . '</p>';
                    }
                if (!empty($insertQuerySuccess)) {
                    echo '<p style="color:green;">' . htmlspecialchars($insertQuerySuccess) . '</p>';
                    }
                    ?>

                <h5 class="text-blue h4">Personal Info</h5>
							<section>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label>First Name :</label>
											<input type="text" class="form-control" name="first_name" />
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label>Last Name :</label>
											<input type="text" class="form-control" name="last_name" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label>Email Address :</label>
											<input type="email" class="form-control" name="email" />
										</div>
									</div>
									<div class="col-md-6">
										<div class="form-group">
											<label>Phone Number :</label>
											<input type="text" class="form-control" name="phone_number" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label>Select County :</label>
											<select class="custom-select form-control" name="county">
												<option value="">Select County</option>
												<option value="Baringo">Baringo</option>
												<option value="Bomet">Bomet</option>
                                                <option value="Bungoma">Bungoma</option>
                                                <option value="Busia">Busia</option>
                                                <option value="Elgeyo-Marakwet">Elgeyo-Marakwet</option>
                                                <option value="Embu">Embu</option>
                                                <option value="Garissa">Garissa</option>
                                                <option value="Homa Bay">Homa Bay</option>
                                                <option value="Isiolo">Isiolo</option>
                                                <option value="Kajiado">Kajiado</option>
                                                <option value="Kakamega">Kakamega</option>
                                                <option value="Kericho">Kericho</option>
                                                <option value="Kiambu">Kiambu</option>
                                                <option value="Kilifi">Kilifi</option>
                                                <option value="Kirinyaga">Kirinyaga</option>
                                                <option value="Kisii">Kisii</option>
                                                <option value="Kisumu">Kisumu</option>
                                                <option value="Kitui">Kitui</option>
                                                <option value="Kwale">Kwale</option>
                                                <option value="Laikipia">Laikipia</option>
                                                <option value="Lamu">Lamu</option>
                                                <option value="Machakos">Machakos</option>
                                                <option value="Makueni">Makueni</option>
                                                <option value="Mandera">Mandera</option>
                                                <option value="Marsabit">Marsabit</option>
                                                <option value="Meru">Meru</option>
                                                <option value="Migori">Migori</option>
                                                <option value="Mombasa">Mombasa</option>
                                                <option value="Murang'a">Murang'a</option>
                                                <option value="Nairobi">Nairobi</option>
                                                <option value="Nakuru">Nakuru</option>
                                                <option value="Nandi">Nandi</option>
                                                <option value="Narok">Narok</option>
                                                <option value="Nyamira">Nyamira</option>
                                                <option value="Nyandarua">Nyandarua</option>
                                                <option value="Nyeri">Nyeri</option>
                                                <option value="Samburu">Samburu</option>
                                                <option value="Siaya">Siaya</option>
                                                <option value="Taita-Taveta">Taita-Taveta</option>
                                                <option value="Tana River">Tana River</option>
                                                <option value="Tharaka-Nithi">Tharaka-Nithi</option>
                                                <option value="Trans Nzoia">Trans Nzoia</option>
                                                <option value="Turkana">Turkana</option>
                                                <option value="Uasin Gishu">Uasin Gishu</option>
                                                <option value="Vihiga">Vihiga</option>
                                                <option value="Wajir">Wajir</option>
                                                <option value="West Pokot">West Pokot</option>
                                            </select>
										</div>
									</div>

									<div class="col-md-6">
										<div class="form-group">
											<label>Town Centre :</label>
											<input type="text" class="form-control" name="town_centre" />
										</div>
									</div>

								</div>
							</section>
							<!-- Step 2 -->
							<h5 class="text-blue h4">KYC Documents</h5>
							<section>
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<label>ID/Passport Number :</label>
											<input type="text" class="form-control" name="national_id" />
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<label>Attach ID (FRONT SIDE) :</label>
											<input type="file" class="form-control-file form-control height-auto" name="id_photo_front" />
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<label>Attach ID (BACK SIDE) :</label>
											<input type="file" class="form-control-file form-control height-auto" name="id_photo_back" />
										</div>
									</div>

								</div>
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<label>NSSF :</label>
											<input type="text" class="form-control" name="nssf" />
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<label>NHIF :</label>
											<input type="text" class="form-control" name="nhif" />
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<label>KRA PIN :</label>
											<input type="text" class="form-control" name="kra_pin" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<label>Date of Onboarding (Enter today's date) :</label>
											<input
												type="text"
												class="form-control date-picker"
												placeholder="Select Date"
												name="date_of_onboarding"
											/>
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<label>Place of Residence (Nearest Building) :</label>
											<input type="text" class="form-control" name="residence_nearest_building" />
										</div>
									</div>
									<div class="col-md-4">
										<div class="form-group">
											<label>Place of Residence (Nearest Road) :</label>
											<input type="text" class="form-control" name="residence_nearest_road" />
										</div>
									</div>
								</div>
							</section>
							<!-- Step 3 -->
							<h5 class="text-blue h4">BIO Data</h5>
							<section>
								<div class="row">
									<div class="col-md-4">
										<div class="form-group">
											<label>Age :</label>
											<input type="text" class="form-control" name="age" />
										</div>
									</div>	
									<div class="col-md-4">
										<div class="form-group">
											<label>Select Gender :</label>
											<select class="custom-select form-control" name="gender">
												<option value="">Select Gender</option>
												<option value="Baringo">Male</option>
												<option value="Bomet">Female</option>
                                                </select>
                                            </div>
                                        </div>
                                </div>								
								<div class="row">
										<div class="col-md-4">
											<div class="form-group">
												<label>Next of Kin Name :</label>
												<input type="text" class="form-control" name="next_of_kin_name" />
											</div>
										</div>
										<div class="col-md-4">
											<div class="form-group">
												<label>Next of Kin Phone Number :</label>
												<input type="text" class="form-control" name="next_of_kin_phone" />
											</div>
										</div>
										<div class="col-md-4">
											<div class="form-group">
												<label>Next of Kin Relation :</label>
												<input type="text" class="form-control" name="next_of_kin_relation" />
											</div>
										</div>	
								</div>
							</section>

							<!-- Step 4 -->
							<h5 class="text-blue h4">Done!!</h5>
							<section>
        <div class="row">
            <p>Please click the "SUBMIT" button. Manager should receive an email with their details and a temporary password. The client can log in to their dashboard using their National ID Number and their password.</p>
        </div>
        <div class="text-center mt-4 form-group mb-0">
        <button type="submit" class="btn btn-primary">Submit: Onboard Manager</button>
        </div>
    </section>
</form>

            </div>
        </div>

        <div class="footer-wrap pd-20 mb-20 card-box">
            Developed by <a href="https://squarehaul.online" target="_blank">Squarehaul</a>
        </div>
    </div>
    <!-- js -->
		<script src="vendors/scripts/core.js"></script>
		<script src="vendors/scripts/script.min.js"></script>
		<script src="vendors/scripts/process.js"></script>
		<script src="vendors/scripts/layout-settings.js"></script>
		<script src="src/plugins/jquery-steps/jquery.steps.js"></script>
</body>
</html>
